#!/bin/sh

xset r rate 170 50
xset b off
xset fp+ /usr/share/fonts/TTF
xset fp+ /usr/share/fonts/local
xset fp rehash

xrdb -merge .Xresources-base16
xrdb -merge .Xresources-fontsizes

setxkbmap us,ru -variant dvp,
xmodmap .xmodmap

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

udiskie --smart-tray &
parcellite --no-icon &
setxkbmap -option caps:escape &

nm-applet &
fluxgui &

ssh-agent awesome
