---
- name: Setup yay Zenbook
  hosts: yay
  become: yes
  become_method: sudo
  vars:
    my_username: shrimpsizemoose
    ssh_keys: https://github.com/cra.keys
    ansible_python_interpreter: "/usr/bin/python3.9"
    run_full_system_upgrade: false
  roles:
    - base
    - pacman
    - aur
    - role: user-settings
      become: yes
      become_user: "{{ my_username }}"
