---

- name: update/upgrade pacman
  pacman:
    update_cache: yes
    upgrade: yes
  when: run_full_system_upgrade

- name: install cli packages
  pacman:
    pkg:
      - base-devel
      - bat
      - bc
      - exa
      - git
      - htop
      - iputils
      - lshw
      - sshfs
      - tmux
      - net-tools
    state: present

- name: add fonts
  pacman:
    pkg:
      - terminus-font
      - otf-fira-code
    state: present

- name: uninstall vim to replace it with neovim
  pacman:
    pkg:
      - vim
    state: absent

- name: install x11org packages
  pacman:
    pkg:
      - awesome
      - evince
      - gvim
      - i3lock
      - neovim
      - networkmanager
      - network-manager-applet
      - otf-fira-code
      - parcellite
      - powerline-vim
      - terminus-font
      - termite
      - udiskie
      - xorg-server
      - xorg-setxkbmap
      - xorg-xev
      - xorg-xinit
      - xorg-xmodmap
      - xorg-xrandr
      - xorg-xrdb
      - xorg-xset
      - xf86-video-intel
    state: present

- name: install browsers
  pacman:
    pkg:
      - code
      - firefox
    state: present

- name: install python stuff
  pacman:
    pkg:
      - flake8
      - ipython
      - jupyter
      - python-black
      - python-pip
      - python-poetry
    state: present

- name: install python convenience packages themes
  pip:
    name:
      - aiohttp
      - aioredis
      - jupyterthemes
      - pyyaml
      - rich
      - rq
      - rq-dashboard
      - ujson

- name: install docker
  pacman:
    pkg:
      - docker
      - docker-compose
    state: present

- name: enable services
  systemd:
    enabled: yes
    name: NetworkManager